export enum EntryTypesIdEnum {
  CONTRIBUTION = 8,
  SAVINGS_DEPOSIT = 11,
  CONTRIBUTION_PENALTY = 6,
  LOAN_CONTRIBUTION = 3,
  LOAN_CONTRIBUTION_PENALTY = 5,
  LOAN_INTEREST = 4,
  STRATEGIC_FUND = 9,
  ADMINISTRATION_FUND = 1,
}
